# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas"
    - OMP_NUM_THREADS=4

before_install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - sudo apt-get update -qq

# Install cmake, OpenMPI, cppcheck
install:
  - sudo apt-get install -y cmake cmake-data openmpi-bin libopenmpi-dev cppcheck

# Test build.sh script
before_script:
  - cmake . -DWITH_MPI=ON
  - make -j4
  - ldd primecount
  - cppcheck src include --error-exitcode=1

# Run primecount tests
script:
  - ./primecount --test
