# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - OMP_NUM_THREADS=4

install:
  - rm -rf primesieve-master*
  - curl -L -o primesieve-master.zip https://github.com/kimwalisch/primesieve/archive/master.zip
  - unzip primesieve-master.zip
  - cd primesieve-master
  - ./autogen.sh
  - ./configure
  - make
  - sudo make uninstall
  - sudo make install
  - cd ..

before_script:
  - ./autogen.sh

script:
  - ./configure CXXFLAGS="-Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -pedantic"
  - make
  - make install
  - make dist
  - make distcheck
