# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  global:
    - CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-missing-braces -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-mismatched-tags"
    - OMP_NUM_THREADS=4

install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake cmake-data openmpi-bin libopenmpi-dev cppcheck valgrind
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi

script:
  - cppcheck src include --error-exitcode=1
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - make -j4
  - make test
  - ldd primecount
  - ./primecount --test
  - ldd test/alpha
  - valgrind --error-exitcode=1 test/alpha
  - valgrind --error-exitcode=1 ./primecount 1e13
  - valgrind --error-exitcode=1 ./primecount 1e11 --deleglise_rivat1
  - valgrind --error-exitcode=1 ./primecount 1e11 --lehmer
  - valgrind --error-exitcode=1 ./primecount 1e10 --lmo3
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. -DWITH_MPI=ON
  - make -j4
  - mpiexec -n 4 ./primecount 1e14 -t1 #| grep 3204941750802
