# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc

env:
  global:
    - OMP_NUM_THREADS=4

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - rm -rf primesieve-master*
  - curl -L -o primesieve-master.zip https://github.com/kimwalisch/primesieve/archive/master.zip
  - unzip primesieve-master.zip
  - cd primesieve-master
  - ./autogen.sh
  - ./configure
  - make
  - sudo make uninstall
  - sudo make install
  - cd ..

before_script:
  - ./autogen.sh

script:
  - ./configure CXXFLAGS="-Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -pedantic -O2"
  - make
  - sudo make install
  - make dist
  - make distcheck
