# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

env:
  global:
    - CXXFLAGS="-O3 -Wall -Wextra -Werror -pedantic -Wno-long-long -Wno-missing-braces"
    - OMP_NUM_THREADS=4

install:
  - sudo apt-get install -y g++-5 make cmake cppcheck valgrind openmpi-bin libopenmpi-dev
  - sudo rm -f /usr/bin/g++
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++

script:
  - cppcheck src include --error-exitcode=1
  - mkdir build
  - cd build
  - if [ "$CXX" = "g++" ]; then cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON; fi
  - if [ "$CXX" = "clang++" ]; then cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DWITH_OPENMP=OFF; fi
  - make -j4
  - make test
  - ldd primecount
  - ./primecount --test
  - ldd test/alpha
  - valgrind --error-exitcode=1 test/alpha
  - valgrind --error-exitcode=1 ./primecount 1e13
  - valgrind --error-exitcode=1 ./primecount 1e11 --deleglise_rivat1
  - valgrind --error-exitcode=1 ./primecount 1e11 --lehmer
  - valgrind --error-exitcode=1 ./primecount 1e10 --lmo3
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - if [ "$CXX" = "clang++" ]; then cmake .. -DWITH_MPI=ON -DWITH_OPENMP=OFF; fi
  - if [ "$CXX" = "g++" ]; then export CXXFLAGS="$CXXFLAGS -Wno-literal-suffix -Wno-strict-aliasing"; fi
  - if [ "$CXX" = "g++" ]; then cmake .. -DWITH_MPI=ON; fi
  - make -j4
  - mpiexec -n 4 ./primecount 1e14 -t1 | grep 3204941750802
