# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - OMP_NUM_THREADS=4

before_install:
  - sudo apt-get update -qq

# Install cmake, OpenMPI, cppcheck
install:
  - sudo apt-get install -y cmake openmpi-bin libopenmpi-dev cppcheck

# Test build.sh script
before_script:
  - ./build.sh -DWITH_MPI=ON
  - ./build.sh
  - ldd primecount
  - cppcheck src include --error-exitcode=1 -i$(cd primesieve-*; basename $(pwd))

# Run primecount tests
script:
  - ./primecount --test
