# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp
dist: xenial

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

env:
  global:
    - CXXFLAGS="-O3 -Wall -Wextra -Werror -pedantic -Wno-long-long -Wno-missing-braces"
    - OMP_NUM_THREADS=4

install:
  - sudo apt-get install -y make cmake cppcheck valgrind openmpi-bin libopenmpi-dev mingw-w64

script:
  # 1) Static analysis using cppcheck
  - cppcheck src include --error-exitcode=1
  # 2) Run test suite
  - mkdir build
  - cd build
  - if [ "$CXX" = "g++" ]; then cmake .. -DBUILD_TESTS=ON; fi
  - if [ "$CXX" = "clang++" ]; then cmake .. -DBUILD_TESTS=ON -DWITH_OPENMP=OFF; fi
  - make -j4
  - make test
  # 3) Print primecount shared library dependencies
  - ldd primecount
  # 4) Run builtin tests
  - ./primecount --test
  # 5) Find runtime memory errors
  - valgrind --error-exitcode=1 ./primecount 1e13
  - valgrind --error-exitcode=1 ./primecount 1e12 --nthprime
  - valgrind --error-exitcode=1 ./primecount 1e11 --deleglise_rivat1
  - valgrind --error-exitcode=1 ./primecount 1e11 --lehmer
  - valgrind --error-exitcode=1 ./primecount 1e10 --lmo3
  # 6) Test primecount MPI
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - if [ "$CXX" = "clang++" ]; then cmake .. -DWITH_MPI=ON -DWITH_OPENMP=OFF; fi
  - if [ "$CXX" = "g++" ]; then cmake .. -DWITH_MPI=ON -DCMAKE_CXX_FLAGS="$CXXFLAGS -Wno-literal-suffix -Wno-strict-aliasing"; fi
  - make -j4
  - mpiexec -n 4 ./primecount 1e14 -t1 | grep 3204941750802
  # 7) Compile using MinGW
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - |
    cmake .. -DCMAKE_SYSTEM_NAME=Windows \
             -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++-posix \
             -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
             -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
             -DBUILD_TESTS=ON
  - make -j4 VERBOSE=1
