# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

env:
  global:
    - OMP_NUM_THREADS=4

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y make openmpi-bin libopenmpi-dev cppcheck valgrind
  - wget --no-check-certificate http://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.3-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.1.3-Linux-x86_64/bin:$PATH
  - if [ "$CXX" = "g++" ]; then export CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-missing-braces -Wno-long-long -Wno-strict-aliasing -Wno-literal-suffix"; fi
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-missing-braces -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas  -Wno-literal-suffix"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9"; fi

script:
  - cppcheck src include --error-exitcode=1 -icmake-3.1.3-Linux-x86_64
  - sed -i 's#CMAKE_BUILD_TYPE Release#CMAKE_BUILD_TYPE Debug#g' CMakeLists.txt
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - make -j4
  - make test
  - ldd primecount
  - ./primecount --test
  - ldd test/alpha
  - valgrind --error-exitcode=1 test/alpha
  - valgrind --error-exitcode=1 ./primecount 1e13
  - valgrind --error-exitcode=1 ./primecount 1e11 --deleglise_rivat1
  - valgrind --error-exitcode=1 ./primecount 1e11 --lehmer
  - valgrind --error-exitcode=1 ./primecount 1e10 --lmo3
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - export CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-missing-braces -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas";
  - cmake .. -DWITH_MPI=ON
  - make -j4
  - mpiexec -n 4 ./primecount 1e14 -t1 | grep 3204941750802
