# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  global:
    - CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-missing-braces -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas"
    - OMP_NUM_THREADS=4

install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake cmake-data openmpi-bin libopenmpi-dev cppcheck valgrind
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi

script:
  - cmake . -DWITH_MPI=ON
  - make -j4
  - ldd primecount
  - cppcheck src include --error-exitcode=1
  - ./primecount --test
  - valgrind --error-exitcode=1 ./primecount 1e14
  - valgrind --error-exitcode=1 ./primecount 1e14 --lmo
  - valgrind --error-exitcode=1 ./primecount 1e10 --lmo3
  - valgrind --error-exitcode=1 ./primecount 1e12 --meissel
  - valgrind --error-exitcode=1 ./primecount 1e12 --lehmer
