# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

platform:
  - x86
  - x64

branches:
  except:
    - gh-pages

os: Visual Studio 2017

build_script:
  - if "%platform%" == "x86" cmake . -G "Visual Studio 15 2017" -DBUILD_TESTS=ON
  - if "%platform%" == "x64" cmake . -G "Visual Studio 15 2017 Win64" -DBUILD_TESTS=ON
  - cmake --build . --config Release

test_script:
  - ctest -C Release
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - test/Release/S2_easy_xy.exe
  - cd Release
  - primecount.exe --test
