# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

platform:
  - x86
  - x64

configuration:
  - Debug

before_build:
  "\"C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Bin\\SetEnv.cmd\" /%platform%"

build_script:
  - cmake -G "NMake Makefiles" .
  - nmake

test_script:
  - primecount.exe --test
